version: '3.5'
services:
  stubby4j-jre11:
    user: root
    image: azagniotov/stubby4j:latest-jre11
    volumes:
      - "./yamls:/home/stubby4j/data"
    container_name: stubby4j_jre11
    ports:
      - 8884:8882
      - 8890:8889
      - 7444:7443
    environment:
      YAML_CONFIG: main-test-stubs.yaml
      LOCATION: 0.0.0.0
      STUBS_PORT: 8882
      ADMIN_PORT: 8889
      STUBS_TLS_PORT: 7443
      WITH_ARGS: "--enable_tls_with_alpn_and_http_2 --debug --watch"
