// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FizzBuzzCalculator is an autogenerated mock type for the FizzBuzzCalculator type
type FizzBuzzCalculator struct {
	mock.Mock
}

// Calculate provides a mock function with given fields: number
func (_m *FizzBuzzCalculator) Calculate(number int) string {
	ret := _m.Called(number)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(number)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
