version: '3.7'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: core-timescale
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: pixie_test
    ports:
      - '9000:5432'