version: '3.7'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test_db
    ports:
      - '9000:5432'